# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.


# cucumber-rails includes Rack::Test::Methods into World by default, which
# shadows ActionDispatch::IntegrationTest's own `post`/`response` (its `post`
# talks to a Rack::Test session, not the Rails integration session, so
# `response` comes back nil). This app has no server-rendered UI -- step
# definitions call the JSON API directly the same way
# test/controllers/api/*_test.rb does (`post`, `response`), so disable the
# Rack::Test helpers to get plain ActionDispatch::IntegrationTest behavior.
ENV['CR_REMOVE_RACK_TEST_HELPERS'] = 'true'

require 'cucumber/rails'

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { except: [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('not @no-txn', 'not @selenium', 'not @culerity', 'not @celerity', 'not @javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

# Step definitions stub PdfGenerator.store/render_pdf (see test/test_helper.rb,
# which does the same for Minitest) since real PDF generation shells out to a
# local Chromium browser via ferrum -- not guaranteed to be present wherever
# this suite runs.
begin
  require 'minitest/mock'
rescue LoadError
  class Object
    def stub(name, val_or_callable, *block_args, **block_kwargs)
      new_name = "__stubbed__#{name}"
      metaclass = class << self; self; end
      metaclass.send :alias_method, new_name, name
      metaclass.send :define_method, name do |*args, **kwargs, &blk|
        if val_or_callable.respond_to?(:call)
          val_or_callable.call(*args, **kwargs, &blk)
        else
          blk&.call(*block_args, **block_kwargs)
          val_or_callable
        end
      end
      yield self
    ensure
      metaclass.send :undef_method, name
      metaclass.send :alias_method, name, new_name
      metaclass.send :undef_method, new_name
    end
  end
end
